### ISSUE TITLE
It does not work at compile.

### ISSUE THREAD

**Issue by gugim-PS** [cb-geo/2d-lbm-dem#1]
At input 'make -JN', there are many error message I have got.
Mostly, undeclared function is occurred.
Could you possibly check this problem or tell me tips to solve? 
Thank you at advance.

**Comment by kks32** [comment]
Hi, The code does compile, see automated CI check: https://circleci.com/gh/cb-geo/2d-lbm-dem/5

Could you share the errors? Unused variables can be safely ignored.

**Comment by kinggu9** [comment]
Error message is too long. 
-------------------------------Start of error message----------------------------------------------------
/home/g/2d-lbm-dem-master/src/main.c:399:49: error: ‘fhf2’ undeclared (first use in this function)
             g[i].a1, g[i].a2, g[i].a3, fhf1[i], fhf2[i], fhf3[i], g[i].p,
                                                 ^
/home/g/2d-lbm-dem-master/src/main.c:399:58: error: ‘fhf3’ undeclared (first use in this function)
             g[i].a1, g[i].a2, g[i].a3, fhf1[i], fhf2[i], fhf3[i], g[i].p,
                                                          ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘write_forces’:
/home/g/2d-lbm-dem-master/src/main.c:430:22: error: ‘g’ undeclared (first use in this function)
   real margin = 10 * g[0].r, hrx1 = 4000, hry2 = 1000;
                      ^
/home/g/2d-lbm-dem-master/src/main.c:433:11: warning: unknown conversion type character ‘B’ in format [-Wformat=]
           hrx1 + margin, hry2 + margin);
           ^
/home/g/2d-lbm-dem-master/src/main.c:434:3: warning: format ‘%C’ expects a matching ‘wint_t’ argument [-Wformat=]
   fprintf(outfile1, "%%%Creator: Krishna Kumar \n");
   ^
/home/g/2d-lbm-dem-master/src/main.c:435:3: warning: unknown conversion type character ‘T’ in format [-Wformat=]
   fprintf(outfile1, "%%%Title: DEM Grains & Forces \n");
   ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘write_densities’:
/home/g/2d-lbm-dem-master/src/main.c:507:14: error: ‘f’ undeclared (first use in this function)
         P += f[x][y][i];
              ^
/home/g/2d-lbm-dem-master/src/main.c:510:11: error: ‘obst’ undeclared (first use in this function)
       if (obst[x][y] < 0) {
           ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘temp_sample’:
/home/g/2d-lbm-dem-master/src/main.c:557:5: error: ‘g’ undeclared (first use in this function)
     g[i].r = r;  //*(real)(i+1)/nbgrains;
     ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘read_sample’:
/home/g/2d-lbm-dem-master/src/main.c:601:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < nbgrains; ++i) {
   ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘check_sample’:
/home/g/2d-lbm-dem-master/src/main.c:628:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < nbgrains; ++i) {
   ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘init_obst’:
/home/g/2d-lbm-dem-master/src/main.c:652:7: error: ‘obst’ undeclared (first use in this function)
       obst[x][y] = -1;
       ^
/home/g/2d-lbm-dem-master/src/main.c:658:5: error: ‘act’ undeclared (first use in this function)
     act[x][0] = act[x][ly - 1] = 0;
     ^
/home/g/2d-lbm-dem-master/src/main.c:667:11: error: ‘g’ undeclared (first use in this function)
     xc = (g[i].x1 - Mgx) / dx;
           ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘init_density’:
/home/g/2d-lbm-dem-master/src/main.c:698:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 0; x < nx; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:699:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int y = 0; y < ny; y++) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:700:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int iLB = 0; iLB < Q; iLB++) {
       ^
/home/g/2d-lbm-dem-master/src/main.c:701:24: error: ‘w’ undeclared (first use in this function)
         f[x][y][iLB] = w[iLB];
                        ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘force_grains’:
/home/g/2d-lbm-dem-master/src/main.c:720:11: error: ‘g’ undeclared (first use in this function)
   xOiOj = g[i].x1 - g[j].x1;
           ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘force_WallB’:
/home/g/2d-lbm-dem-master/src/main.c:794:8: error: ‘g’ undeclared (first use in this function)
   vn = g[i].v2;
        ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘force_WallT’:
/home/g/2d-lbm-dem-master/src/main.c:830:8: error: ‘g’ undeclared (first use in this function)
   vn = g[i].v2;
        ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘force_WallL’:
/home/g/2d-lbm-dem-master/src/main.c:872:8: error: ‘g’ undeclared (first use in this function)
   vn = g[i].v1;
        ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘force_WallR’:
/home/g/2d-lbm-dem-master/src/main.c:907:8: error: ‘g’ undeclared (first use in this function)
   vn = g[i].v1;
        ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘reinit_obst_density’:
/home/g/2d-lbm-dem-master/src/main.c:948:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 1; x < lx - 1; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:949:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int y = 1; y < ly - 1; y++) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:950:15: error: ‘obst’ undeclared (first use in this function)
       int i = obst[x][y];
               ^
/home/g/2d-lbm-dem-master/src/main.c:954:24: error: ‘g’ undeclared (first use in this function)
         real u_squ = ((g[i].v1 - (y * dx + Mby - g[i].x2) * g[i].v3) * (g[i].v1 - (y * dx + Mby - g[i].x2) * g[i].v3)
                        ^
/home/g/2d-lbm-dem-master/src/main.c:956:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int iLB = 0; iLB < Q; iLB++) {
         ^
/home/g/2d-lbm-dem-master/src/main.c:961:11: error: ‘f’ undeclared (first use in this function)
           f[x][y][iLB] = w[iLB] * (1. + 3 * eu + 4.5 * eu * eu - 1.5 * u_squ);  //*rho_moy;
           ^
/home/g/2d-lbm-dem-master/src/main.c:961:26: error: ‘w’ undeclared (first use in this function)
           f[x][y][iLB] = w[iLB] * (1. + 3 * eu + 4.5 * eu * eu - 1.5 * u_squ);  //*rho_moy;
                          ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘obst_construction’:
/home/g/2d-lbm-dem-master/src/main.c:978:7: error: ‘obst’ undeclared (first use in this function)
       obst[x][y] = -1;
       ^
/home/g/2d-lbm-dem-master/src/main.c:979:7: error: ‘act’ undeclared (first use in this function)
       act[x][y] = 1;
       ^
/home/g/2d-lbm-dem-master/src/main.c:981:9: error: ‘delta’ undeclared (first use in this function)
         delta[x][y][iLB] = 0;
         ^
/home/g/2d-lbm-dem-master/src/main.c:986:11: error: ‘g’ undeclared (first use in this function)
     xc = (g[i].x1 - Mgx) / dx;
           ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘collision_streaming’:
/home/g/2d-lbm-dem-master/src/main.c:1054:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 1; x < lx - 1; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1055:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int y = 1; y < ly - 1; y++) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:1056:11: error: ‘obst’ undeclared (first use in this function)
       if (obst[x][y] == -1) {
           ^
/home/g/2d-lbm-dem-master/src/main.c:1058:20: error: ‘f’ undeclared (first use in this function)
         real rho = f[x][y][0] + f[x][y][1] + f[x][y][2] + f[x][y][3] + f[x][y][4]
                    ^
/home/g/2d-lbm-dem-master/src/main.c:1099:12: error: redefinition of ‘x’
   for (int x = 1; x < lx - 1; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1054:12: note: previous definition of ‘x’ was here
   for (int x = 1; x < lx - 1; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1099:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 1; x < lx - 1; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1108:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int y = 1; y < ly - 1; y++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1130:12: error: redefinition of ‘x’
   for (int x = 1; x < lx - 1; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1099:12: note: previous definition of ‘x’ was here
   for (int x = 1; x < lx - 1; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1130:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 1; x < lx - 1; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1131:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int y = 1; y < ly - 1; y++) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:1133:22: error: ‘act’ undeclared (first use in this function)
       if (i != -1 && act[x][y] == 1) {
                      ^
/home/g/2d-lbm-dem-master/src/main.c:1134:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int iLB = 1; iLB <= half; iLB++) {
         ^
/home/g/2d-lbm-dem-master/src/main.c:1138:28: error: ‘w’ undeclared (first use in this function)
             f[x][y][iLB] = w[iLB];
                            ^
/home/g/2d-lbm-dem-master/src/main.c:1142:17: error: ‘delta’ undeclared (first use in this function)
             if (delta[x][y][iLB] >= 0.5) {
                 ^
/home/g/2d-lbm-dem-master/src/main.c:1148:35: error: ‘g’ undeclared (first use in this function)
                       (ex[iLB] * (g[i].v1 - (y * dx + Mby - g[i].x2) * g[i].v3) +
                                   ^
/home/g/2d-lbm-dem-master/src/main.c:1165:18: error: redefinition of ‘iLB’
         for (int iLB = 1 + half; iLB < Q; iLB++) {
                  ^
/home/g/2d-lbm-dem-master/src/main.c:1134:18: note: previous definition of ‘iLB’ was here
         for (int iLB = 1; iLB <= half; iLB++) {
                  ^
/home/g/2d-lbm-dem-master/src/main.c:1165:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int iLB = 1 + half; iLB < Q; iLB++) {
         ^
/home/g/2d-lbm-dem-master/src/main.c:1200:12: error: redefinition of ‘x’
   for (int x = 0; x < lx; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1130:12: note: previous definition of ‘x’ was here
   for (int x = 1; x < lx - 1; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1200:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 0; x < lx; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1201:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int y = 0; y < ly; y++) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:1202:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int iLB = 1; iLB <= half; iLB++) {
       ^
/home/g/2d-lbm-dem-master/src/main.c:1208:12: error: redefinition of ‘x’
   for (int x = 0; x < lx; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1200:12: note: previous definition of ‘x’ was here
   for (int x = 0; x < lx; x++) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1208:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int x = 0; x < lx; x++) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1209:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int y = 0; y < ly; y++) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:1210:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int iLB = 1; iLB <= half; iLB++) {
       ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘check_density’:
/home/g/2d-lbm-dem-master/src/main.c:1231:21: error: ‘f’ undeclared (first use in this function)
         sum = sum + f[x][y][iLB];
                     ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘final_density’:
/home/g/2d-lbm-dem-master/src/main.c:1244:21: error: ‘f’ undeclared (first use in this function)
         sum = sum + f[x][y][iLB];
                     ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘forces_fluid’:
/home/g/2d-lbm-dem-master/src/main.c:1264:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < nbgrains; ++i) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1265:5: error: ‘fhf1’ undeclared (first use in this function)
     fhf1[i] = 0;
     ^
/home/g/2d-lbm-dem-master/src/main.c:1266:5: error: ‘fhf2’ undeclared (first use in this function)
     fhf2[i] = 0;
     ^
/home/g/2d-lbm-dem-master/src/main.c:1267:5: error: ‘fhf3’ undeclared (first use in this function)
     fhf3[i] = 0;
     ^
/home/g/2d-lbm-dem-master/src/main.c:1270:12: error: redefinition of ‘i’
   for (int i = 0; i < nbgrains; ++i) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1264:12: note: previous definition of ‘i’ was here
   for (int i = 0; i < nbgrains; ++i) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1270:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < nbgrains; ++i) {
   ^
/home/g/2d-lbm-dem-master/src/main.c:1280:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int x = xi; x <= xf; ++x) {
     ^
/home/g/2d-lbm-dem-master/src/main.c:1281:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int y = yi; y <= yf; ++y) {
       ^
/home/g/2d-lbm-dem-master/src/main.c:1282:18: error: ‘obst’ undeclared (first use in this function)
         if (i != obst[x][y]) continue;
                  ^
/home/g/2d-lbm-dem-master/src/main.c:1284:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int iLB = 1; iLB < Q; ++iLB) {
         ^
/home/g/2d-lbm-dem-master/src/main.c:1302:12: error: redefinition of ‘i’
   for (int i = 0; i < nbgrains; ++i) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1270:12: note: previous definition of ‘i’ was here
   for (int i = 0; i < nbgrains; ++i) {
            ^
/home/g/2d-lbm-dem-master/src/main.c:1302:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < nbgrains; ++i) {
   ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘acceleration_grains’:
/home/g/2d-lbm-dem-master/src/main.c:1324:7: error: ‘g’ undeclared (first use in this function)
       g[i].a1 = fhf1[i];
       ^
/home/g/2d-lbm-dem-master/src/main.c:1324:17: error: ‘fhf1’ undeclared (first use in this function)
       g[i].a1 = fhf1[i];
                 ^
/home/g/2d-lbm-dem-master/src/main.c:1325:17: error: ‘fhf2’ undeclared (first use in this function)
       g[i].a2 = fhf2[i];
                 ^
/home/g/2d-lbm-dem-master/src/main.c:1326:17: error: ‘fhf3’ undeclared (first use in this function)
       g[i].a3 = fhf3[i];
                 ^
/home/g/2d-lbm-dem-master/src/main.c:1339:29: error: ‘neighbours’ undeclared (first use in this function)
         xOiOj = g[i].x1 - g[neighbours[j]].x1;
                             ^
/home/g/2d-lbm-dem-master/src/main.c:1430:12: error: ‘neighbourWallB’ undeclared (first use in this function)
     dn = g[neighbourWallB[i]].x2 - g[neighbourWallB[i]].r - Mby;
            ^
/home/g/2d-lbm-dem-master/src/main.c:1447:13: error: ‘neighbourWallT’ undeclared (first use in this function)
     dn = -g[neighbourWallT[i]].x2 - g[neighbourWallT[i]].r + Mhy;
             ^
/home/g/2d-lbm-dem-master/src/main.c:1458:12: error: ‘neighbourWallL’ undeclared (first use in this function)
     dn = g[neighbourWallL[i]].x1 - g[neighbourWallL[i]].r - Mgx;
            ^
/home/g/2d-lbm-dem-master/src/main.c:1475:13: error: ‘neighbourWallR’ undeclared (first use in this function)
     dn = -g[neighbourWallR[i]].x1 - g[neighbourWallR[i]].r + Mdx;
             ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘initVerlet’:
/home/g/2d-lbm-dem-master/src/main.c:1501:15: error: ‘g’ undeclared (first use in this function)
       distx = g[i].x1 - g[j].x1;
               ^
/home/g/2d-lbm-dem-master/src/main.c:1507:11: error: ‘neighbours’ undeclared (first use in this function)
           neighbours[jneighbours] = j;
           ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘VerletWall’:
/home/g/2d-lbm-dem-master/src/main.c:1538:10: error: ‘g’ undeclared (first use in this function)
     dn = g[i].x2 - g[i].r - Mby;
          ^
/home/g/2d-lbm-dem-master/src/main.c:1540:7: error: ‘neighbourWallB’ undeclared (first use in this function)
       neighbourWallB[nNeighWallb] = i;
       ^
/home/g/2d-lbm-dem-master/src/main.c:1548:7: error: ‘neighbourWallT’ undeclared (first use in this function)
       neighbourWallT[nNeighWallt] = i;
       ^
/home/g/2d-lbm-dem-master/src/main.c:1556:7: error: ‘neighbourWallL’ undeclared (first use in this function)
       neighbourWallL[nNeighWallL] = i;
       ^
/home/g/2d-lbm-dem-master/src/main.c:1564:7: error: ‘neighbourWallR’ undeclared (first use in this function)
       neighbourWallR[nNeighWallR] = i;
       ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘obst_writing’:
/home/g/2d-lbm-dem-master/src/main.c:1583:32: error: ‘obst’ undeclared (first use in this function)
       fprintf(outfile1, "%d ", obst[x][y]);
                                ^
/home/g/2d-lbm-dem-master/src/main.c:1595:32: error: ‘act’ undeclared (first use in this function)
       fprintf(outfile2, "%d ", act[x][y]);
                                ^
/home/g/2d-lbm-dem-master/src/main.c:1608:13: error: ‘delta’ undeclared (first use in this function)
         if (delta[x][y][i] != 0) {
             ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘velocity_profile’:
/home/g/2d-lbm-dem-master/src/main.c:1632:14: error: ‘g’ undeclared (first use in this function)
   y = (int)((g[0].x2 - Mby) / dx);
              ^
/home/g/2d-lbm-dem-master/src/main.c:1634:9: error: ‘obst’ undeclared (first use in this function)
     if (obst[x][y] != -1 && obst[x][y] != nbgrains)
         ^
/home/g/2d-lbm-dem-master/src/main.c:1640:25: error: ‘f’ undeclared (first use in this function)
         d_loc = d_loc + f[x][y][i];
                         ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘pressures’:
/home/g/2d-lbm-dem-master/src/main.c:1659:11: error: ‘obst’ undeclared (first use in this function)
       if (obst[x][y] == -1) {
           ^
/home/g/2d-lbm-dem-master/src/main.c:1660:9: error: ‘press’ undeclared (first use in this function)
         press[x][y] =
         ^
/home/g/2d-lbm-dem-master/src/main.c:1661:14: error: ‘f’ undeclared (first use in this function)
             (f[x][y][0] + f[x][y][1] + f[x][y][2] + f[x][y][3] + f[x][y][4] +
              ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘renderScene’:
/home/g/2d-lbm-dem-master/src/main.c:1691:28: error: ‘f’ undeclared (first use in this function)
       forces_fluid(lx, ly, f, nbgrains, g);
                            ^
/home/g/2d-lbm-dem-master/src/main.c:1691:41: error: ‘g’ undeclared (first use in this function)
       forces_fluid(lx, ly, f, nbgrains, g);
                                         ^
/home/g/2d-lbm-dem-master/src/main.c: In function ‘main’:
/home/g/2d-lbm-dem-master/src/main.c:1773:3: error: ‘g’ undeclared (first use in this function)
   g = read_sample(argv[1]);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1776:3: error: ‘f’ undeclared (first use in this function)
   f = malloc(sizeof(real)*lx*ly*Q); assert(f);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1778:3: error: ‘obst’ undeclared (first use in this function)
   obst = malloc(sizeof(int)*lx*ly); assert(obst);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1779:3: error: ‘act’ undeclared (first use in this function)
   act = malloc(sizeof(int)*lx*ly); assert(act);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1780:3: error: ‘delta’ undeclared (first use in this function)
   delta = malloc(sizeof(real)*lx*ly*Q); assert(delta);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1784:3: error: ‘neighbours’ undeclared (first use in this function)
   neighbours = malloc(sizeof(int)*nbgrains*6); assert(neighbours);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1785:3: error: ‘neighbourWallB’ undeclared (first use in this function)
   neighbourWallB = malloc(sizeof(int)*nbgrains); assert(neighbourWallB);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1786:3: error: ‘neighbourWallR’ undeclared (first use in this function)
   neighbourWallR = malloc(sizeof(int)*nbgrains); assert(neighbourWallR);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1787:3: error: ‘neighbourWallL’ undeclared (first use in this function)
   neighbourWallL = malloc(sizeof(int)*nbgrains); assert(neighbourWallL);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1788:3: error: ‘neighbourWallT’ undeclared (first use in this function)
   neighbourWallT = malloc(sizeof(int)*nbgrains); assert(neighbourWallT);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1803:3: error: ‘fhf’ undeclared (first use in this function)
   fhf = malloc(sizeof(struct force)*nbgrains); assert(fhf);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1804:3: error: ‘fhf1’ undeclared (first use in this function)
   fhf1 = malloc(sizeof(real)*nbgrains); assert(fhf1);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1805:3: error: ‘fhf2’ undeclared (first use in this function)
   fhf2 = malloc(sizeof(real)*nbgrains); assert(fhf2);
   ^
/home/g/2d-lbm-dem-master/src/main.c:1806:3: error: ‘fhf3’ undeclared (first use in this function)
   fhf3 = malloc(sizeof(real)*nbgrains); assert(fhf3);
   ^
make[2]: *** [CMakeFiles/lbmdem.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/lbmdem.dir/all] Error 2
make: *** [all] Error 2
-------------------------------END of error message--------------------------------------------------------

**Comment by kinggu9** [comment]
Hello again,
I solved the problem I asked you. 
So, one more question as execute.
When input './bin/lbmdem /<path-to-inputfile>/inputfile.dat' for execute, I' ve got message 'No such file or directory'.
how can I solve it?
