### ISSUE TITLE
As execute

### ISSUE THREAD

**Issue by gugim-PS** [cb-geo/2d-lbm-dem#2]
Hello again,
I solved the problem I asked you.
So, one more question as execute.
When input './bin/lbmdem //inputfile.dat' for execute, I' ve got message 'No such file or directory'.
how can I solve it?

**Comment by kks32** [comment]
To execute the LBM code run `./bin/lbdem ./spl04.data`. If you are using the sample file in the local bin directory.

**Comment by gugim-PS** [comment]
Thank you!
I would like to know 
how to make sample data file to represent particle point randomly or regularly?

**Comment by kks32** [comment]
You can use a custom script to generate coordinates.
